# Site settings
title: Sobha Hillview Apartment Owners Association
description: Welcome to our community website.
theme: just-the-docs

# Build settings
remote_theme: pmarsceill/just-the-docs

# Enable search and other theme options
just_the_docs:
  logo: /assets/images/sobha-hillview.png # Optional: Add a logo
  search_enabled: true
  # Set the base URL for your site
  url: https://sobha-hillview.github.io
  baseurl: "" # Leave empty unless your site is in a subdirectory

# Exclude files or directories from processing
exclude:
  - index.md

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown processing
markdown: md
