# Site settings
title: Sobha Hillview Apartment Owners Association
description: Welcome to our community website.
url: https://sobha-hillview.github.io
baseurl: "" # Leave this empty unless your site is in a subdirectory

theme: just-the-docs

# Build settings
remote_theme: pmarsceill/just-the-docs

# Enable built-in search
just_the_docs:
  search_enabled: true

# (Optional) Set the base URL if your site is not at the root of the domain
# baseurl: "/sobha-hillview.github.io"

# (Optional) Specify the URL of your site
# url: "https://sobha-hillview.github.io"

# Navigation links
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Amenities"
    url: "/amenities/"
  - title: "Security"
    url: "/security/"
  - title: "Daily Help"
    url: "/daily-help/"
  - title: "Schools"
    url: "/nearby-schools/"
  - title: "Parks"
    url: "/nearby-parks/"
  - title: "Banks"
    url: "/nearby-banks/"
  - title: "Location"
    url: "/location/"
  - title: "Contact"
    url: "/contact/"

sass:
  sass_dir: _sass

# Social media links (optional)
social_links:
  - name: "Facebook"
    url: "https://www.facebook.com/sobha-hillview"
  - name: "Twitter"
    url: "https://twitter.com/sobha-hillview"

# Plugins
plugins:
  - jekyll-feed

# Exclude files or directories from processing
exclude:
  - README.md

# Markdown processing
markdown: kramdown

# Optional settings
# Uncomment and set if needed
# paginate: 5
# paginate_path: "/page:num/"
